DROP TABLE IF EXISTS users, categories, locations, events;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    annotation        VARCHAR(1024) NOT NULL,
    category_id       BIGINT        NOT NULL REFERENCES categories ON DELETE CASCADE,
    confirmedRequests BIGINT,
    createdOn         VARCHAR(19),
    description       VARCHAR(4096),
    eventDate         VARCHAR(19)   NOT NULL,
    initiator_id      BIGINT        NOT NULL REFERENCES users ON DELETE CASCADE,
    location_id       BIGINT        NOT NULL REFERENCES locations ON DELETE CASCADE,
    paid              BOOL          NOT NULL,
    participantLimit  INTEGER,
    publishedOn       VARCHAR(19),
    requestModeration BOOL,
    state             VARCHAR(64),
    title             VARCHAR(256)  NOT NULL,
    views             BIGINT
);